name: Deployment

on:
  push:
    branches: [ main ]

env:

  DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  USER: ${{ secrets.EC2_REMOTE_HOST }}
  HOST: ${{ secrets.EC2_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v1

      - name: Container registry setup
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: riccskn/devops-test:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName ec2-3-18-111-48.us-east-2.compute.amazonaws.com
            User $USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
      - name: List home directory
        run: ssh ec2 'ls -la'