name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          if [ "$USERNAME" == "HENRICKE" ]
          then
            echo "hiiiiiiiiiiiiii"
