name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKER_HUB_USERNAME }}"