name: Deployment

on:
  push:
    branches: [ main ]

env:

  DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1

      - name: Container registry setup
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
           username: ${{ env.DOCKER_USER }}
           password: ${{ env.DOCKER_PASSWORD }}
        
